apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
stringData:
  PGUSER: "postgres"
  PGHOST: "localhost"
  PGPASSWORD: "password"
  PGDATABASE: "database"
  PGPORT: "5432"
  JWT_SECRET: "jwt_secret"
