apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: monolith
    service: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
      service: database
  template:
    metadata:
      labels:
        app: monolith
        service: database
    spec:
      containers:
        - name: database
          image: postgres:alpine
          env:
            name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: POSTGRES_PASSWORD
          volumeMounts:
            - name: database
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: database
          hostPath:
            path: /Users/willpower/Documents/kubernates/db
